### ISSUE TITLE
LICENSE for ionelmc/cookiecutter-pylibrary

### ISSUE THREAD

**Issue by rcuza** [ionelmc/cookiecutter-pylibrary#101]
Feature request: please add a LICENSE for your repo.

This will make it easier for me to use your template at work. If you don't have a preference ISC/BSD style licenses are preferred.

Thank you for sharing your work. It is helping me improve my python skills.

**Comment by ionelmc** [comment]
Feel free to use the 2-clause BSD licensed template then :)
