### ISSUE TITLE
Question: where is the variable TOXPYTHON used?

### ISSUE THREAD

**Issue by jdkent** [ionelmc/cookiecutter-pylibrary#105]
I generated a project with this cookie cutter (thanks!) and I'm trying to get a handle on how everything is set up. 

One thing that I'm having trouble finding documentation on is the use of the environment variable TOXPYTHON. Where is this variable used and why is it important?

If anyone could point me towards some information I would be very grateful.

**Comment by ionelmc** [comment]
It's used here: https://github.com/ionelmc/cookiecutter-pylibrary/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/tox.ini#L33-L39

It exists to allow 32bin/64bin specialization on windows (mostly for CI purposes). Eg: on a machine that has both 32 and 64 bits interpreters you need to have a way to tell tox "use the other interpreter".

**Comment by jdkent** [comment]
Thank you @ionelmc! I'm mostly focusing on building with linux so I haven't yet considered the idiosyncrasies with windows. This was helpful.

**Comment by dHannasch** [comment]
Looking at https://github.com/ionelmc/cookiecutter-pylibrary/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/tox.ini#L40-L47...if TOXPYTHON is set, doesn't that mean only one version of Python is actually tested?

**Comment by ionelmc** [comment]
If it's set then yes, it will override the basepython regardless of tox environment. This is only meant to be used in situations where you run a single tox env and you want to specialize the python bin (eg: 32 vs 64bit, or a specific installation of python).
