### ISSUE TITLE
Documentation Issue

### ISSUE THREAD

**Issue by ayushjsh** [ionelmc/cookiecutter-pylibrary#110]
I have created a package using your cookiecutter and am not sure if the sphynx documentation is working.
In your docs/references/nameless.rst , you have 

`automodules::nameless 
:: members
`
I am assuming it should fetch the docstrings from the modules within the nameless package and render them as HTML. However I do not see it in your readthedocs as well as the one generated by me. 
Is it a sys.path issue in Sphynx conf.py?

**Comment by ayushjsh** [comment]
I do think I am misisng an __all__ but I am not sure if I need it.

here is a link to the repository:
https://gitlab.com/deeprd/python-fhrs

also here is a link to the Readthedocs:
https://python-fhrs.readthedocs.io/en/latest/

I was hoping that some of the methods in my fhrs class which were documented would show up in the documentation. 

Really like your cookiecutter overall!

**Comment by ionelmc** [comment]
Your code is in `fhrs.fhrs` not in `fhrs`. Change this: https://gitlab.com/deeprd/python-fhrs/blob/master/docs/reference/fhrs.rst#L8

Also, you should have an `__all__`.

**Comment by ayushjsh** [comment]
Thanks for the quick reply! Also thanks for helping me, I am still getting to learn advanced python concepts.

I have now solved my issue! 

Thank you for your help.
