### ISSUE TITLE
Development status defaults to "Production/Stable"

### ISSUE THREAD

**Issue by jtrakk** [ionelmc/cookiecutter-pylibrary#115]
In setup.py development status is set to "Production/Stable", which is not where I am when I first generate a project from template :-).

**Comment by ionelmc** [comment]
Would you like a cookiecutter.json option for that? Make a concrete proposal :)

**Comment by jtrakk** [comment]
Yes I think an option would be good.

**Comment by ionelmc** [comment]
Feel free to make PR if you still want this.
