### ISSUE TITLE
spell testenv fails: "The 'enchant' C library was not found"

### ISSUE THREAD

**Issue by cmeeren** [ionelmc/cookiecutter-pylibrary#12]
`tox -e spell` fails with the following error: `Could not import extension sphinxcontrib.spelling (exception: The 'enchant' C library was not found. Please install it via your OS package manager, or use a pre-built binary wheel from PyPI.)`

Full log:

```
$ tox -e spell
spell create: C:\Users\Christer\code\python\latexdiffcite\.tox\spell
spell installdeps: -rC:\Users\Christer\code\python\latexdiffcite/docs/requirements.txt, sphinxcontrib-spelling, pyenchant
spell develop-inst: C:\Users\Christer\code\python\latexdiffcite
spell installed: alabaster==0.7.4,Babel==1.3,colorama==0.3.3,docutils==0.12,Jinja2==2.7.3,latexdiffcite==0.9.0,MarkupSafe==0.23,pockets==0.2.4,pyenchant==1.6.6,Pygments==2.0.2,pytz==2015.4,six==1.9.0,snowballstemmer==1.2.0,Sphinx==1.3.1,sphinx-rtd-theme==0.1.8,sphinxcontrib-napoleon==0.3.6,sphinxcontrib-spelling==2.1.1,wheel==0.24.0
spell runtests: PYTHONHASHSEED='242'
spell runtests: commands[0] | sphinx-build -b spelling docs dist/docs
Running Sphinx v1.3.1

Extension error:
Could not import extension sphinxcontrib.spelling (exception: The 'enchant' C library was not found. Please install it via your OS package manager, or use a pre-built binary wheel from PyPI.)
ERROR: InvocationError: 'C:\\Users\\Christer\\code\\python\\latexdiffcite\\.tox\\spell\\Scripts\\sphinx-build.EXE -b spelling docs dist/docs'
___________________________________ summary ___________________________________
ERROR:   spell: commands failed
```

Excerpt from my `tox.ini`:

```
[testenv:spell]
setenv =
    SPELLCHECK = 1
commands =
    sphinx-build -b spelling docs dist/docs
usedevelop = true
deps =
    -r{toxinidir}/docs/requirements.txt
    sphinxcontrib-spelling
    pyenchant
```

Using Windows 7 64 bit, launching `tox` from Python 3.4.

**Comment by ionelmc** [comment]
Looks like there aren't 64bit wheels for windows: https://pypi.python.org/pypi/pyenchant/

See https://github.com/rfk/pyenchant/issues/42

**Comment by cmeeren** [comment]
Shouldn't that cause installation to fail? I managed to install it just fine in my normal python distribution using ``pip install pyenchant``:

```
Collecting pyenchant
  Using cached pyenchant-1.6.6-py2.py3-none-any.whl
Installing collected packages: pyenchant
Successfully installed pyenchant-1.6.6
```

**Comment by ionelmc** [comment]
Yes but `pyenchant-1.6.6-py2.py3-none-any.whl` is the generic non-binary wheel. It won't work on Windows unless you have the 64bit DLL copied somewhere on your PATH.

**Comment by cmeeren** [comment]
When you say *the* 64 bit DLL, does that mean there exists one which I can get? Or will I have to build one?

**Comment by ionelmc** [comment]
No idea. I just use Ubuntu for this sort of stuff.

**Comment by cmeeren** [comment]
Chancing on closing this since it's not related to this package...

**Comment by Querela** [comment]
Hi,
I can't seem to get PyEnchant to work ...
I'm working on a Linux system: `Linux ### 4.9.80-c9 #1 SMP Wed Feb 7 08:47:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux` but even after googling and testing various commands I was not able to get it to work. (compiling it from source was not nearly as trivial or possible? as it was described on their homepage ...)
Is there hope for a simple, stupid solution? Or simply remove it?

But great work with the template, even if it is a more private project and the whole publishing and badges etc. can't easily be used... 😀

**Comment by cscli** [comment]
sudo yum install enchant -y  , done
