### ISSUE TITLE
Mention and link to semantic versioning

### ISSUE THREAD

**Issue by cmeeren** [ionelmc/cookiecutter-pylibrary#14]
I, in my blissful ignorance, see no reason why anyone creating a new project using this template has any reason NOT to use [semantic versioning](http://semver.org/). The website says:

> If all of this sounds desirable, all you need to do to start using Semantic Versioning is to declare that you are doing so and then follow the rules. Link to this website from your README so others know the rules and can benefit from them.

I propose that you add something to that effect to the readme and link to the website.

**Comment by ionelmc** [comment]
Hmm, looks like I don't have an introduction to `bumpversion` neither. Are you familiar with that tool?

**Comment by cmeeren** [comment]
I did install it and looked at the usage, and I have set it up for my project and will use it going forward (unless something better comes my way), but I have never used it before.

**Comment by cmeeren** [comment]
:+1: 

Oh and I really like the

> No way, this is the best. :stuck_out_tongue_winking_eye:

Totally agree. No, seriously. This has really kickstarted my Python packaging "career". Thanks!
