### ISSUE TITLE
tox -e check fails if date is entered in long form

### ISSUE THREAD

**Issue by dHannasch** [ionelmc/cookiecutter-pylibrary#140]
If a date is entered in long form such as 8 July 2016, tox -e check fails:
```
warning: Check: The project's long_description has invalid markup which will not be rendered on PyPI. The following syntax errors were detected:
line 161: Warning: Title underline too short.

0.0.0 (8 July 2016)
------------------
```

**Comment by ionelmc** [comment]
We could have something like in here: https://github.com/ionelmc/cookiecutter-pylibrary/commit/592ea9be62b8d445519ade9d8852926a10ba966e

**Comment by ionelmc** [comment]
Ah ... didn't notice 141.

**Comment by dHannasch** [comment]
`{{ "-" * datestring|length }}` like in https://github.com/ionelmc/cookiecutter-pylibrary/commit/592ea9be62b8d445519ade9d8852926a10ba966e would work too. I didn't know you could do that. I don't know if there are advantages or disadvantages.
