### ISSUE TITLE
Scrutinizer usage

### ISSUE THREAD

**Issue by cmeeren** [ionelmc/cookiecutter-pylibrary#15]
You include a Scrutinizer code quality badge in the readme. Is there any reason why Scrutinizer is not used for more than code quality? Coverage, CI, etc. Is everything else on Scrutinizer only for paying customers? (I don't see them advertising anything as free at all, yet still code quality is obviously free, so I have no idea what is and what isn't free.)

**Comment by ionelmc** [comment]
It's not very nice, you have to deal with access tokens:
https://scrutinizer-ci.com/docs/tools/external-code-coverage/#python


Thanks,
-- Ionel Cristian Mărieș, http://blog.ionelmc.ro

**Comment by cmeeren** [comment]
The page you linked to concerns sending coverage data from another build process to Scrutinizer. I am talking about using scrutinizer on its own, as a CI with integrated coverage report etc. I think it requires a subscription, though as said I'm not sure what's free and what's not.

**Comment by ionelmc** [comment]
Seems not:
https://scrutinizer-ci.com/tour/continuous-integration-and-deployment-made-easy
:-)

Do you have a concrete proposal here?

I added all them badges so I don't have to figure out the service/badge url
every time I want said service. Users would remove badges they don't need.
Ideally cookiecutter would have a nice multi-select input but sadly, it
doesn't have that yet.


Thanks,
-- Ionel Cristian Mărieș, http://blog.ionelmc.ro

**Comment by cmeeren** [comment]
> Seems not:

Do you mean "seems it doesn't require a subscription"? Because I don't see that anywhere, all I see is "start your free trial". In fact, I just stumbled across [this page](https://scrutinizer-ci.com/docs/build/code_coverage), which says:

> Note: This guide details how to generate code coverage when using Scrutinizer as your CI service (paid plans only). Please refer to [sending external code coverage](https://scrutinizer-ci.com/docs/tools/external-code-coverage/) if you are using Scrutinizer for automated code reviews only.

So it seems to me that automated code reviews might be the only free service Scrutinizer offers.

In general, I didn't have a concrete proposal (at this time), I just wondered whether it was an active decision on your part to not use Scrutinizer for more than automated code review (if it was free, which it seems to me now it isn't :disappointed: ).

**Comment by ionelmc** [comment]
Naa, I'm not against it. As a mater of fact, I'm playing a bit with codecov (as an alternative to coveralls) right now.

**Comment by cmeeren** [comment]
Codecov looks very nice. Let me know if you choose to use that instead. (Feel free to make a pull request at https://github.com/cmeeren/latexdiffcite/ if you update the config, I'll happily try it out!)

**Comment by ionelmc** [comment]
You could regenerate the boilerplate by running `cookiecutter gh:ionelmc/cookiecutter-pylibrary --checkout=develop` (the codecov changes are in the develop branch). Then just revert the changes you don't need (easy with `git gui`).

How about that? If that's too annoying you should complain in the cookiecutter issue tracker :)

**Comment by cmeeren** [comment]
Looks good, I'll take it!

How about also doing coverage on AppVeyor? I see that codecov supports it (when adding a repo, it says that the upload token is "not required on Travis, AppVeyor or Circle CI"). That might display more accurate coverage for some projects using OS-specific code.

**Comment by cmeeren** [comment]
I don't really understand the "partial coverage", though. It seems broken. Take a look [here](https://codecov.io/github/cmeeren/latexdiffcite/src/latexdiffcite/latexdiffcite.py?ref=feature/codecov), line 256 and 277. Simple ``if`` statements, the code inside them is executed, but the conditions themselves are only partially covered. Do you think that is a bug?

**Comment by ionelmc** [comment]
I think this explains the partial lines: http://nedbatchelder.com/code/coverage/branch.html

**Comment by cmeeren** [comment]
Thanks, I understand now.

**Comment by cmeeren** [comment]
Well would you look at that. I find a line partially covered and think *oh, it's completely pointless to test that, but I do want 100% coverage*, and I make a test and whaddaya know, I discover a bug. Go codecov!

**Comment by ionelmc** [comment]
So coveralls doesn't support partial coverage?

**Comment by cmeeren** [comment]
Not that I can see. People are wishing for in on the issues list, but no support yet.

**Comment by ionelmc** [comment]
I think I'm gonna make codecov  the default then :)

**Comment by cmeeren** [comment]
:+1:

**Comment by kaidokert** [comment]
Two more badges that i add to my own projects, that are not in the template yet : Codacy and CodeClimate. All of them find slightly different issues, with pretty minimum configuration required. PR ?

**Comment by ionelmc** [comment]
@kaidokert do it. Add configuration flags for it. Don't forget to update the README.rst
