### ISSUE TITLE
Duplicated coverage report on COVERALLS

### ISSUE THREAD

**Issue by joaomcteixeira** [ionelmc/cookiecutter-pylibrary#158]
Hi @ionelmc 

*quick words of introduction:* I have been reading during the last days through your documentation, posts and projects related to this cookiecutter and packaging strategy. In the beginning every line was new information and I could only learn it going line by line and [build my own skeleton repository the hard way](https://github.com/joaomcteixeira/python-project-skeleton). I really support your strategy!

*Going to the issue:*

I generated [this repo](https://github.com/joaomcteixeira/python-bioplottemplates) from this cookiecutter. As is, the coverage information is reported twice to COVERALLS, coming from both Travis and Appveyor, rendering this [awkward output](https://coveralls.io/github/joaomcteixeira/python-bioplottemplates) of duplicated file information.

I encountered this same behavior during the first commits of my first skeleton repository (mentioned above). Finally I solved it after restricting sending coverage reports only through Travis (see [.travis.yml](https://github.com/joaomcteixeira/python-project-skeleton/blob/0c6c64cd36b954989a29cb836acb778ab18ff545/.travis.yml#L63-L68)) and removing `env:coverage` and `env:coveralls` from `tox.in`.

**first question:** Where is travis sending coverage information to coveralls? Is it through the `env:coveralls` ? (same to codecov?)

**question 2:** why sending coverage information from both appveyor and travis?

**solution:** depending on your answers, can this be changed in the coockiecutter template?

Thank you!

**Comment by ionelmc** [comment]
1. Yes, it's coveralls env in tox.ini

2. Looks like there is an issue with how coveralls is merging the report from appveyor (looks like it doesn't merge at all 😞 - imo this is a bug in coveralls). I've recently added the coveralls support in the appveyor configuration, maybe I should have added with with a disable flag. Alternatively we can just change the template a bit so if coveralls_token ain't set then it's disabled in appveyor (it won't work without the token anyway).

**Comment by joaomcteixeira** [comment]
* Is it a problem if coverage report for codecov and coveralls is done only in one of the platforms, either Travis or AppVeyor? 
* I think it works without the token. [In this repo](https://github.com/joaomcteixeira/python-project-skeleton) I did not specify the tokens anywhere. It reports just for what is specified in the `.travis.yml` file. Truth is, in this example, I remove the coveralls and codecov envs from tox and do not perform it in AppVeyor. Can you comment on this so I better understand why this strategy is a bad strategy (though I am using it I am not convinced it is the best). Also, from the [docs](https://docs.travis-ci.com/user/coveralls/) and [here (not official docs)](https://medium.com/datadriveninvestor/beginners-guide-to-using-codecov-with-python-and-travis-ci-c17659bb711) it really seams token is only needed for private repositories

**Comment by ionelmc** [comment]
Coveralls has been switched to their new github action. Open new issue if there's a problem with that.
