### ISSUE TITLE
Why 32 bit only on AppVeyor, not Travis?

### ISSUE THREAD

**Issue by cmeeren** [ionelmc/cookiecutter-pylibrary#16]
I see that AppVeypor is set up with both 32 and 64 bit Python versions. I can't see that Travis is set up with 32 bit (it uses 64 bit as default, as far as I know). Is there a good reason for this?

**Comment by ionelmc** [comment]
It's just a Linux idiosyncrasy - no one really uses 32bit python on 64bit OS. You'll have a very hard time finding a distro offering that. There are virtually no use-cases for that - people usually distribute code, not binaries (like on Windows).

On Windows it's a different story, Microsoft is obsessed with backwards compatibility (that's how they keep the users after all) - thus, running 32bit apps on 64bit OS is the order of the day ;-)
