### ISSUE TITLE
Upgrade CI config from xenial to bionic

### ISSUE THREAD

**Issue by ionelmc** [ionelmc/cookiecutter-pylibrary#165]
It looks like that means dropping python 3.5: https://docs.travis-ci.com/user/reference/bionic/

**Comment by dHannasch** [comment]
Are you thinking this might also fix #161?

**Comment by ionelmc** [comment]
Well the CI on pylibrary is way older (trusty). Even if upgrading don't fix it we gotta upgrade it anyway ... trusty is ancient.
