### ISSUE TITLE
Allow the use of travis windows environment instead of appveyor

### ISSUE THREAD

**Issue by qlixed** [ionelmc/cookiecutter-pylibrary#174]
As there is now support on windows enviroment I thing that it will be useful to add this option. I rather prefer to have all in one CI, and I think that I'm not the only one :smile:
I'm trying to get a grasp of the code you generate to see if I can make this happen, but maybe is something quite basic to make for you as is your code!.

**Comment by ionelmc** [comment]
Take a look at the travis_osx option. Either way take a look at: https://travis-ci.community/t/current-known-issues-please-read-this-before-posting-a-new-topic/264/5

**Comment by ionelmc** [comment]
Travis and appveyor are gone.
