### ISSUE TITLE
Include  .readthedocs.yml in MANIFEST.in

### ISSUE THREAD

**Issue by nealmcb** [ionelmc/cookiecutter-pylibrary#182]
I got this build error:

```
lists of files in version control and sdist do not match!                                
missing from sdist:                                                                                                                                           
  .readthedocs.yml
```

 It went away when I included `.readthedocs.yml` in the MANIFEST.in

**Comment by dHannasch** [comment]
Want to open a pull request to add it to https://github.com/ionelmc/cookiecutter-pylibrary/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/MANIFEST.in#L10 ?
