### ISSUE TITLE
Switch to autoapi from autodoc

### ISSUE THREAD

**Issue by nealmcb** [ionelmc/cookiecutter-pylibrary#187]
I was surprised to see that autodoc, as used in Sphinx, doesn't automate as much as I expected. It requires individually listing modules, ongoing maintenance based on new modules, and requires installing dependencies just to produce documentation.

Based on the advice to use `autoapi` at [Sphinx autodoc is not automatic enough](https://stackoverflow.com/a/57860910/507544), I tried it and love it.

See the necessary diffs changes in our PR: [r2b2 repo: Switch to autoapi from autodoc by nealmcb · Pull Request \#7](https://github.com/gwexploratoryaudits/r2b2/pull/7)

**Comment by ionelmc** [comment]
I tried autoapi - it [works](https://python-tblib.readthedocs.io/en/latest/autoapi/tblib/index.html) but I think it should be an option. Perhaps `sphinx_autoapi` or `sphinx_reference=(autoapi|autodoc)`. What do you think? You interested in making a PR?

**Comment by nealmcb** [comment]
Thanks for checking it out.

Supporting it via an option sounds good, and offhand having a `sphinx_reference` like that seems clear and flexible. I'll leave the default to you, but suggest it be made clear somehow what you get with each.

Sorry - I don't have time now to put a PR together.
