### ISSUE TITLE
Out of Box: tox step 'docs' gets error ERROR: InterpreterNotFound: 

### ISSUE THREAD

**Issue by DiesDasJenes** [ionelmc/cookiecutter-pylibrary#198]
Aloha,

i started learning python and i downloaded the latest version of this template via cookiecutter with the command `cookiecutter gh:ionelmc/cookiecutter-pylibrary`. 

When i run `tox -e docs` or `tox` i get :

```
docs create: /Users/username/*/*/python-gem_webcrawl_datafilterer/.tox/docs
SKIPPED: InterpreterNotFound:
__________________________________________________________________________________________________________________ summary ___________________________________________________________________________________________________________________
SKIPPED:  docs: InterpreterNotFound:
```
This also fails on travis CI.

I removed some of the python env's in the tox.ini config but besides that i didn't change the configuration of the tox steps. 
(file is here:https://github.com/DiesDasJenes/python-gem_webcrawl_datafilterer/blob/master/tox.ini). 

In the .tox folder was no 'docs' folder created. To mitigate the problem i added the flag: "skip_missing_interpreter".

What do i need to do for the 'docs' step to succeed and the .tox/docs folder to be created? 

Thanks for help. :)

**Comment by ionelmc** [comment]
I guess it was a wrong idea to hardcode python3.6 in tox.ini for the docs env (was a CI workaround). I will fix this, meanwhile you can just replace that with python3 I guess.

**Comment by DiesDasJenes** [comment]
Thanks for the fast answer. 
I added 'docs' to the list for {env:TOXPYTHON:python3}. This fixed my problem.
In the travis.yml i also set the version to 3.7 for python.
```
[testenv]
basepython =
    py37: {env:TOXPYTHON:python3.7}
    py38: {env:TOXPYTHON:python3.8}
    py39: {env:TOXPYTHON:python3.9}
    {bootstrap,clean,check,docs,report,codecov}: {env:TOXPYTHON:python3}
setenv =
    PYTHONPATH={toxinidir}/tests
    PYTHONUNBUFFERED=yes
    SETUPPY_CFLAGS=-DCYTHON_TRACE=1
passenv =
    *
usedevelop = false
deps =
    pytest
    pytest-travis-fold
    pytest-cov
commands =
    {posargs:pytest --cov --cov-report=term-missing -vv tests}
```

**Comment by ionelmc** [comment]
I still need to fix it.
