### ISSUE TITLE
Python versions support

### ISSUE THREAD

**Issue by BjoernLudwigPTB** [ionelmc/cookiecutter-pylibrary#200]
I just prepared the very minor PR #199 and noticed that tox runs against Python 2.7 and Python 3.6, whereas the utilised image is based on Python 3.7. Why not have it run against the upstream supported Python versions 3.5 to 3.8. And... since Python 2 reached its EOL in January, do you really want to keep it in here? I just wanted to suggest to drop Python 2 support because of that, to keep things aligned with the surrounding developments. Of course this could be done, as soon as the first problems arise, but then maybe people would expect problems to be solved.

**Comment by ionelmc** [comment]
Dropping Python 2 has to wait - I still have some Python 2 projects around. I'm looking the the CI issue. Note that this is kinda doubly-tested, ci also run at https://travis-ci.org/github/ionelmc/python-nameless/branches for a bunch of configurations.

**Comment by BjoernLudwigPTB** [comment]
Ah yes, I see. Then it would probably as well be fine to just leave it as it is, or suffice to match the image's Python version to the one Python 3 version in the root's tox configuration (either both 3.6 or both 3.7)?!
