### ISSUE TITLE
The cookiecutter project does not offer options for non-open source projects

### ISSUE THREAD

**Issue by bf4648** [ionelmc/cookiecutter-pylibrary#21]
The project offers awesome options for open source projects that are completely free such as appveyor, travis ci, coveralls, and codedov but it does not offer offer alternatives for projects that are in-house or that are not open source.  It would be nice to know some of the free alternatives that are out there for non-open source projects.

**Comment by bf4648** [comment]
Maybe there could be an option in the set up process to ask if this is an in-house project that will not be shared on PyPI

**Comment by ionelmc** [comment]
A good start is https://en.wikipedia.org/wiki/Comparison_of_continuous_integration_software

However that misses some other services, eg:
* https://about.gitlab.com/gitlab-ci/
* https://buildkite.com/
* https://github.com/PCManticore/argus-ci

and probably others ...

**Comment by dragon788** [comment]
You can also use Travis-CI.com instead of .org if you are doing a private repository project, so I think that at least for Travis the configuration would be the same other than the site where you actually configure the project build.

**Comment by ionelmc** [comment]
Note that if you use `repo_hosting!="github"` various things like CI or badges may be broken.

**Comment by ionelmc** [comment]
Also, `repo_hosting="no"` will remove badges.
