### ISSUE TITLE
Possible skip logic issue on codacy question?

### ISSUE THREAD

**Issue by TSSlade** [ionelmc/cookiecutter-pylibrary#242]
Given my understanding of the README, I would have expected question `#36` to be skipped in light of my response to question `#35`. It appears it was not?

![image](https://github.com/ionelmc/cookiecutter-pylibrary/assets/3211478/172bf5bd-47e6-41a9-a423-fc9fb737216d)

**Comment by ionelmc** [comment]
It's not possible, cookiecutter  doesn't allow such flexibility. Just
ignore that question - press enter :-)

**Comment by TSSlade** [comment]
Ah, indeed, I'd misread this:
> Fields that work together usually use the same prefix. If you answer "no" on the first one then the rest won't have any effect so just ignore them. Maybe in the future cookiecutter will allow option hiding or something like a wizard.

Thanks!
