### ISSUE TITLE
Have a flag to use setuptools_scm

### ISSUE THREAD

**Issue by ionelmc** [ionelmc/cookiecutter-pylibrary#25]
Hmmm

**Comment by psteinb** [comment]
See #103 for another thread on this. I feel `versioneer` is a bit more flexible than setuptools_scm as it doesn't require carrying the relative path to the top level folder of the package. For example, see the [setuptools_scm docs](https://pypi.org/project/setuptools-scm/)

> In order to use `setuptools_scm` from code that is one directory deeper than the project’s root, you can use:
> ~~~~
> from setuptools_scm import get_version
> version = get_version(root='..', relative_to=__file__)
> ~~~~

For versioneer, it's just the following anywhere
```
import versioneer
aversion = versioneer.get_version()
```

**Comment by dHannasch** [comment]
I'd like to us setuptools_scm to avoid the need for MANIFEST.in, but when I set setup_py_uses_setuptools_scm="yes", my CI runner chokes when trying to run `tox -e py27`:
```
python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-yuMrtS/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-yuMrtS/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-req-build-yuMrtS/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-yuMrtS/setup.py", line 36, in <module>
        re.sub(':[a-z]+:`~?(.*?)`', r'``\1``', read('CHANGELOG.rst'))
      File "/tmp/pip-req-build-yuMrtS/setup.py", line 21, in read
        encoding=kwargs.get('encoding', 'utf8')
    IOError: [Errno 2] No such file or directory: '/tmp/pip-req-build-yuMrtS/CHANGELOG.rst'
```
Strangely, this only happens inside the Docker container; I cannot reproduce this locally. Investigation is ongoing.

Regenerating the package with setup_py_uses_setuptools_scm="no" and setting MANIFEST.in manually makes everything run fine.

**Comment by ionelmc** [comment]
What version of pip you have there?

**Comment by ionelmc** [comment]
@psteinb Looks like I forgot to respond. So I've picked setuptools-scm because of it's setuptools integration (automatic baking of version file during build, and the automatic manifest magic). Versioneer could still be an option if you wanna help out.

**Comment by dHannasch** [comment]
> What version of pip you have there?

...that is an excellent question, I really should have that at my fingertips. I've now copied the --version checks from .travis.yml so I'll always know that going forward.
```
$ git --version
git version 2.22.0
$ python3 --version
Python 3.7.3
$ virtualenv --version
16.7.5
$ pip3 --version
pip 19.2.3 from /usr/lib/python3.7/site-packages/pip (python 3.7)
```
