### ISSUE TITLE
No such file or directory: 'ci/appveyor-bootstrap.ps1'

### ISSUE THREAD

**Issue by kputland** [ionelmc/cookiecutter-pylibrary#26]
Traceback (most recent call last):
  File "/var/folders/5q/24r8h7nn2cn0_vbz9x454xfr0000gp/T/tmp42pow7.py", line 9, in <module>
    os.unlink(join('ci', 'appveyor-bootstrap.ps1'))
OSError: [Errno 2] No such file or directory: 'ci/appveyor-bootstrap.ps1'

**Comment by ionelmc** [comment]
Gonna fix this soon. Meanwhile you can use the latest tag. Eg `cookiecutter gh:ionelmc/cookiecutter-pylibrary -c v1.9`

**Comment by kputland** [comment]
Thanks,

I had a copy of that tag already.

Other suggestion is to support namespace packages.
I can create them, but there's a bit of fixup I need to do after your
cookiecutter.

foo.libbar

and other project

foo.libbaz

--Karl

Karl Putland
Senior Engineer
*SimpleSignal*
Anywhere: 303-242-8608
<http://www.simplesignal.com/explainer_video.php>

**Comment by ionelmc** [comment]
What fixes do you do for namespaces?

**Comment by kputland** [comment]
so if I say create package

package_name:             'foo.bar'


It currently creates a directory foo.bar
I then

mkdir foo
mv foo.bar.py foo/bar.py

cat > foo/__init__.py << EOF
#! /usr/bin/env python

import pkg_resources
pkg_resources.declare_namespace(__name__)
EOF

and fix up a couple path references in setup.py


--Karl







Karl Putland
Senior Engineer
*SimpleSignal*
Anywhere: 303-242-8608
<http://www.simplesignal.com/explainer_video.php>

**Comment by ionelmc** [comment]
I see what you want but I don't think it's possible with cookiecutter :(

**Comment by ionelmc** [comment]
Hold on, it might be possible via https://github.com/ionelmc/cookiecutter-pylibrary/blob/master/hooks/post_gen_project.py (we'd just do a mkdir+rename there). Want to contribute? :grin:

**Comment by kputland** [comment]
There's at least one stale reference to a cookiecutter when I search for
it. Other references are for pyscaffold which can use cookiecutter but I
haven't explored that much.

https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=python%20package%20namespace%20cookiecutter

But if your post_gen hook works, that could be a temporary workaround...
Maybe a new parameter

package_namespace: foo
package_name: bar

create bar using normal cookiecutter mechanisms, then create namespace and
relocate bar.
Would need to monkey with paths and references to bar to replace with
foo/bar or foo.bar where appropriate.

--Karl

Karl Putland
Senior Engineer
*SimpleSignal*
Anywhere: 303-242-8608
<http://www.simplesignal.com/explainer_video.php>

**Comment by ionelmc** [comment]
Closing this cause the initial problem is fixed. If you still want the namespace thing we can talk on a new issue.
