### ISSUE TITLE
Where to put project dependencies?

### ISSUE THREAD

**Issue by cmeeren** [ionelmc/cookiecutter-pylibrary#29]
I am unsure where to put project dependencies (e.g. numpy). Options:

* docs/requirements.txt
* tox.ini (under `[testenv]`)
* setup.py (`install_requires`)
* other places?

**Comment by ionelmc** [comment]
* abstract deps (no version or bounded versions like `foo>=1.2.3`) should do in setup.py/install_requires. New releases of deps should not require new releases of your package (unless you completely mistrust your deps, quite unlikely :grimacing:)
* pinned (aka concrete) deps (`foo==1.2.3`) should go in tox.ini (that way you also get notifications from 
http://requires.io). Updating the deps also triggers new test runs in Travis/AppVeyor - this is the reason you pin them: reproducible test results.
* docs/reqs.txt only exists for readthedocs (that's how it works)

Does this answer your question?

**Comment by cmeeren** [comment]
Yes I think so. But if bounded versions have an _upper_ bound, wouldn't a service like requires.io also make sense in that case?

**Comment by ionelmc** [comment]
Yes. You do need to know exactly wich concrete deps you tested with no?

**Comment by cmeeren** [comment]
Maybe this is an error with cookiecutter-pylibrary, maybe it's my configuration: I have added `numpy` to `install_requires` in `setup.py`. In `setup.cfg` I have added

    dependencies =
        np1.9: numpy==1.9
        np1.8: numpy==1.8

But after running the tests on Travis and AppVeyor I get weird results. See this build job on [Travis](https://travis-ci.org/cmeeren/aacgmv2/builds/83117034) and [AppVeyor](https://ci.appveyor.com/project/cmeeren/aacgmv2/build/master-38). On Travis, the ``nocover`` jobs run fine, but the numpy build/install fails on the other jobs for some reason. On AppVeyor, other jobs fail (which have passed the tests on my local Windows machine).

Do you have any idea what could be wrong?

**Comment by cmeeren** [comment]
For Travis, the reason seems to be the ``CFLAGS=-coverage`` environment variable in tox.ini (removed in [this build](https://travis-ci.org/cmeeren/aacgmv2/builds/83256857)). It seems numpy does not like this flag when compiling from source. Removing it will remove C coverage from codecov ([before](https://codecov.io/github/cmeeren/aacgmv2/?ref=efae2f429198aac5390c42c374e38e6f79639240&view=all), [after](https://codecov.io/github/cmeeren/aacgmv2/?ref=9676e1bc02381663e7c63fbc9cc4e7180365bbc2&view=all)), though coveralls will still cover C code ([after](https://coveralls.io/builds/3730995)).

I have yet to find out why the AppVeyor build fails on 3.3-np1.8, 3.4-np1.8 and 3.5 (both numpy versions).

**Comment by ionelmc** [comment]
Assuming you want C coverage for your C code (and not numpy's) then we'd need to set that env var only in the scope where your C code is getting compiled.

I think the most portable way (unfortunately) is to set a "CCOV" env var in your tox.ini and then check for that in setup.py (and set CFLAGS in os.environ). That would ensure the var is set for your C code.

**Comment by cmeeren** [comment]
Thanks, I'll try that. I found out that the reason numpy doesn't like it is because it overwrites numpy's own CFLAGS variable.

As for AppVeyor, I found known issues regarding compiling numpy 1.8 on Python 3.3 and 3.4, and probably both 1.8 and 1.9 on Python 3.5. So that's to be expected.

**Comment by cmeeren** [comment]
Is there a way I could exclude these specific tests from AppVeyor? Or allow them to fail? I haven't found a way to do this due to how the configuration files are set up.

**Comment by ionelmc** [comment]
You could add some checks here: https://github.com/cmeeren/aacgmv2/blob/master/ci/templates/appveyor.yml#L11

I'm sorry there isn't a cleaner way :)

**Comment by cmeeren** [comment]
Thanks, I ended up using the following (after I figured out I could use environment variables as conditions):

```
matrix:
  allow_failures:
    - TOXENV: 'check'
    - TOXENV: '3.3-np1.8-nocover'
    - TOXENV: '3.3-np1.8,codecov'
    - TOXENV: '3.4-np1.8-nocover'
    - TOXENV: '3.4-np1.8,codecov'
    - TOXENV: '3.5-np1.8-nocover'
    - TOXENV: '3.5-np1.8,codecov'
    - TOXENV: '3.5-np1.9-nocover'
    - TOXENV: '3.5-np1.9,codecov'
```

**Comment by ionelmc** [comment]
@cmeeren do I need to fix anything more here?

**Comment by cmeeren** [comment]
Nope. :smiley_cat:
