### ISSUE TITLE
local building of docs and dependencies

### ISSUE THREAD

**Issue by Midnighter** [ionelmc/cookiecutter-pylibrary#30]
My current project has one dependency which I mention in `install_requires` in `setup.py`. I also have the package available in my virtual environment and thus `sphinx-build` runs just fine. `tox -e docs`, however, fails locally but seems to do just fine on Read the Docs. It fails locally because the dependency cannot be imported. I tried adding my dependency to `docs/requirements.txt` as well but that didn't solve the issue. Any ideas?

**Comment by ionelmc** [comment]
@Midnighter did you try to run `tox -e docs -r`? If you updated your `setup.py` or `docs/requiremetns.txt` after you ran `tox -e docs` then it's quite likely the tox env is stale.

**Comment by Midnighter** [comment]
That did the trick. Thanks a lot.
