### ISSUE TITLE
Multiprocessing fix on Travis

### ISSUE THREAD

**Issue by cmeeren** [ionelmc/cookiecutter-pylibrary#31]
On [this page](https://gist.github.com/dan-blanchard/7045057) I came across the following which is meant to fix multiprocessing on Travis:

    before_install:
      - sudo rm -rf /dev/shm
      - sudo ln -s /run/shm /dev/shm

I haven't tested multiprocessing on Travis, so I don't know if it's actually broken or if the fix works, but I thought I'd let you know.

**Comment by ionelmc** [comment]
Interesting, I've done this too long time ago in python-tblib:
```
  - sudo rm -rf /dev/shm || /bin/true# see https://github.com/travis-ci/travis-core/issues/187
  - sudo ln -Tsf /{run,dev}/shm || /bin/true
```
But that issue don't exist anymore - they closed the issue tracker :rage:

**Comment by ionelmc** [comment]
Lets see if this blows up: https://travis-ci.org/ionelmc/python-tblib/builds/83278948

**Comment by ionelmc** [comment]
It seems to work fine (without the shm fix), even on container infra (https://travis-ci.org/ionelmc/python-tblib/builds/97604729). Closing.
