### ISSUE TITLE
Why not skip_install = true in environment "docs"?

### ISSUE THREAD

**Issue by cmeeren** [ionelmc/cookiecutter-pylibrary#34]
Why is not `skip_install = true` in the tox environment `docs`? It works fine when I add it.

**Comment by cmeeren** [comment]
Oh nevermind, [autodoc](http://sphinx-doc.org/ext/autodoc.html) requires the module to be installed.

**Comment by ionelmc** [comment]
Sphinx might need to import your code. Eg: if you use [autodoc](http://sphinx-doc.org/ext/autodoc.html?highlight=autofunction#module-sphinx.ext.autodoc).

**Comment by ionelmc** [comment]
:grin:
