### ISSUE TITLE
Use pip cache on AppVeyor and Travis

### ISSUE THREAD

**Issue by cmeeren** [ionelmc/cookiecutter-pylibrary#38]
[Speed up pip install](http://blog.ionelmc.ro/2015/01/02/speedup-pip-install/) is a really great idea. Caches are supported on both [Travis](http://docs.travis-ci.com/user/caching/) and [AppVeyor](http://www.appveyor.com/docs/build-cache). It would be great if you could enable caching so it works locally and at Travis and AppVeyor!

(I'm developing an extension that depends on numpy, which takes quite a while to compile each time...)

**Comment by ionelmc** [comment]
This should be solved by https://github.com/ionelmc/cookiecutter-pylibrary/pull/36, at least for Travis.

Doesn't it work?

**Comment by cmeeren** [comment]
Probably - I'm still on an old version of cookiecutter-pypackage. However I'd really like to see this for AppVeyor as well, since [fully testing my aacgmv2 package with no cache takes 1-2 full days](https://ci.appveyor.com/project/cmeeren/aacgmv2) due to building numpy.

**Comment by cmeeren** [comment]
Oh, and if it could work locally as well, that would be swell.

**Comment by ionelmc** [comment]
Try https://pypi.python.org/pypi/cookiepatcher to update project.

**Comment by cmeeren** [comment]
Thanks! The configuration files are rather heavily changed though, don't know how well it will work in this specific case. Will keep it in mind for the future, though!

**Comment by cmeeren** [comment]
Are you planning on implementing this on AppVeyor or locally?

**Comment by ionelmc** [comment]
Yes, on my long TODO list :grimacing:. Wouldn't mind if someone else do it :yum:

**Comment by cmeeren** [comment]
I see that appveyor.yml already has

````
cache:
  - '%LOCALAPPDATA%\pip\Cache'
````

Is this all that's needed? In other words, is AppVeyor caching already implemented? Ref. https://github.com/ionelmc/cookiecutter-pylibrary/pull/36 to see how it was implemented for Travis.

**Comment by cmeeren** [comment]
Also, from what I can see from the [pip changelog](https://pip.pypa.io/en/stable/news/#release-notes), it automatically builds and caches wheels since 7.0.0. If this is true, and it's already implemented on AppVeyor, then there's really nothing to do here and this issue can be closed.

**Comment by ionelmc** [comment]
Let me verify this
