### ISSUE TITLE
Allow no Creation of Documentation (docs dir)

### ISSUE THREAD

**Issue by tomschr** [ionelmc/cookiecutter-pylibrary#45]
Great project! :+1: 

When you are asked by cookiecutter, you can only decide which Sphinx theme you would like to use.

However, some projects create there documentation without Sphinx or use different tools. For that reason, it would be nice to have a  `use_doc` entry in `cookiecutter.json` (or something similar). If `yes` (default) is selected, the usual process is executed. With `no`, no `docs` directory is created and any Sphinx theme is skipped.

Does that make sense? :smiley:

**Comment by ionelmc** [comment]
It kinda makes sense. I did use this template on projects with no docs, but in that case I just deleted the docs directory. Do you really think the template needs an option for this?

**Comment by ionelmc** [comment]
My issue with another option (`use_docs` or whatever) is that cookiecutter is still going to ask about the theme. 

We could have a "no" option for `sphinx_theme` tho ...

**Comment by tomschr** [comment]
Oh, wow, that was quick! Thanks for your answer.

Well, sure, the easiest would be to delete the `docs` dir completely. However, sometimes you have other connections, for example with `tox` where you can explicitly build the doc. So deleting the dir is not enough, you have to twiddle on some more locations.


> We could have a "no" option for sphinx_theme tho ...

That was also my first idea, but for the sake of clarity, it could be a bit misleading. That's why I thought a special  `use_doc` key would be more clear.

> My issue with another option (use_docs or whatever) is that cookiecutter is still going to ask about the theme.

I guess, if it's easier for you, I don't mind. The only thing would be to have something to disable the doc dir generation and maybe some targets for tox (if this is used).

Thanks!

**Comment by ionelmc** [comment]
> That was also my first idea, but for the sake of clarity, it could be a bit misleading. That's why I thought a special use_doc key would be more clear.

What if there was a "WITHOUT DOCS" option there in the theme list?

I don't really like either way, that's why I suggested to just remove the dir. 

What other docs system do you use? Maybe we should just support that?

**Comment by tomschr** [comment]
> What if there was a "WITHOUT DOCS" option there in the theme list?

Would also work. :-)


> I don't really like either way, that's why I suggested to just remove the dir. 

Me neither, but if cookiecutter doesn't allow more fine-grained decisions, we have to live with one of this.

Not sure if docs is also used in tox. So removing just the directory is probably not enough. You have also to remove any occurance of doc building from `tox.ini`.

> What other docs system do you use? Maybe we should just support that?

Thanks, it's DocBook. :) However, it's not mainstream anymore and there are many ways to build it.

**Comment by dragon788** [comment]
Just commenting because I'm curious about this as well. Personally I think I'd prefer to write my documentation in Markdown and use something like pypandoc in a pipeline to output the .rst files for Sphinx to build from, but that's just because Markdown has been easier for me to learn than the "stronger" LaTex/ReST syntax.

**Comment by ionelmc** [comment]
PyPI doesn't support Markdown, so at the very least it's not a good default choice. Still, I'd accept a PR with markdown docs, provided caveats (`long_description` needs different source in `setup.py`) are made note of somewhere.

**Comment by ionelmc** [comment]
Hmmm looks like I forgot to close this. There is the `sphinx_docs="no"` option.
