### ISSUE TITLE
readthedocs strips dots from repo_name

### ISSUE THREAD

**Issue by Djiit** [ionelmc/cookiecutter-pylibrary#47]
Hi,

When using ReadTheDocs with a repo_name containing dots ("."), it strips them i.e. : "nameless.py" gives "namelesspy.readthedocs.org" and "namelesspy.rtfd.org"

ReadTheDocs link is then broken in README.rst. We should strip dots from readthedocs links; but I'm not sure how to do it...

Thx

**Comment by ionelmc** [comment]
Try now.

**Comment by Djiit** [comment]
Working like a charm :) thx !
