### ISSUE TITLE
Commenting out python versions breaks tox

### ISSUE THREAD

**Issue by lgpage** [ionelmc/cookiecutter-pylibrary#57]
Contents of `setup.cfg`:

```
...
python_versions =
    2.7
    #3.3
    #3.4
    #3.5
    #pypy
...
```

Contents of `tox.ini`:

```
[testenv:#3.3-cover]
basepython = {env:TOXPYTHON:python#3.3}
setenv =
    {[testenv]setenv}
    WITH_COVERAGE=yes
    SETUPPY_CFLAGS=-coverage
usedevelop = true
commands =
    python setup.py clean --all build_ext --force --inplace
    {posargs:py.test --cov --cov-report=term-missing -vv}
deps =
    {[testenv]deps}
    pytest-cov
```

Of course the easy fix it to delete python versions and not comment them out.

**Comment by ionelmc** [comment]
It should work as expected if you comment from beginning of line (no
leading spaces) I think ...

On Monday, 4 April 2016, lgpage <notifications@github.com> wrote:

> Contents of setup.cfg:
>
> ...
> python_versions =
>     2.7
>     #3.3
>     #3.4
>     #3.5
>     #pypy
> ...
>
> Contents of tox.ini:
>
> [testenv:#3.3-cover]
> basepython = {env:TOXPYTHON:python#3.3}
> setenv =
>     {[testenv]setenv}
>     WITH_COVERAGE=yes
>     SETUPPY_CFLAGS=-coverage
> usedevelop = true
> commands =
>     python setup.py clean --all build_ext --force --inplace
>     {posargs:py.test --cov --cov-report=term-missing -vv}
> deps =
>     {[testenv]deps}
>     pytest-cov
>
> Of course the easy fix it to delete python versions and not comment them
> out.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ionelmc/cookiecutter-pylibrary/issues/57>
>


-- 

Thanks,
-- Ionel Cristian Mărieș, http://blog.ionelmc.ro

**Comment by ionelmc** [comment]
Should work fine now, switched to new configparser.
