### ISSUE TITLE
Adding test dependencies

### ISSUE THREAD

**Issue by Midnighter** [ionelmc/cookiecutter-pylibrary#59]
I have two packages, one pytest plugin and scipy, that I need in the test environments.  I don't want them to be part of the test matrix. So where is the best place to add them? I could edit the `tox.ini` but that seems silly since that file is automatically generated. So is there a better place for it?

**Comment by ionelmc** [comment]
If you're using `test_matrix_generator=yes` then you can either edit the template in `ci/templates` or `setup.cfg`.

If you're using `test_matrix_generator=no` then I can only assume you regenerate the whole project with cookiecutter. I'm not sure this happens often enough to warrant special support ...

Also, you might be tempted to use a `requirements.txt` file and have `deps = -rrequirements.txt` in `tox.ini` however I dislike that way cause if you change something in `requirements.txt` tox can't detect the change so you have to remember to manually regenerate the virtualenv (`tox -r`).

**Comment by Midnighter** [comment]
Thank you for your answer. I'm using `test_matrix_generator=yes`, so editing either the `tox.ini` template or `setup.cfg` seems to be the way forward.

The `ci/templates/tox.ini` has a section:

```
[testenv]
...
deps =
    pytest
    pytest-travis-fold
```

which is where I want my dependencies to go. So I can easily edit the template but that doesn't *feel* right. Is there a way to achieve the same thing with `setup.cfg`, though? I don't want to add any of these dependencies to

```
[matrix]
...
dependencies =
```

**Comment by ionelmc** [comment]
> So I can easily edit the template but that doesn't feel right. 

I've been doing this in all the projects I have (that use `test_matrix_generator=yes`) - it's not *that* bad.

**Comment by Midnighter** [comment]
Fair enough. Thank you for your time.
