### ISSUE TITLE
Delayed Compilation of Extensions

### ISSUE THREAD

**Issue by Midnighter** [ionelmc/cookiecutter-pylibrary#60]
Hi, I've been playing around with Cython and C extensions a lot lately and one issue that bugs me again and again is availability of Cython and inclusion of headers. Your package does a good job of checking for Cython and falling back to pre-compiled `*.c` sources when it's not found but one thing that's still missing is delayed building of extensions that, for example, depend on the `numpy` headers which still need to be installed.

`matplotlib` has a [solution here](https://github.com/matplotlib/matplotlib/blob/master/setupext.py#L809) and I was wondering if that's interesting to you? If yes, I can work on a pull request that would add this feature.

**Comment by ionelmc** [comment]
Hmm interesting. I haven't packaged myself anything that needs that sort of thing (like something that would link against numpy) so I'm wondering what's the demand for this sort of thing ...

It would certainly make the resulting `setup.py` quite big.

Perhaps a `c_extension_delayed_include` option in `cookiecutter.json`? The alternative is just documenting this technique in the [readme](https://github.com/ionelmc/cookiecutter-pylibrary#questions-answers).

Regarding matplotlib's technique - it seems  over-engineered to me, this could had worked just as well at a fraction of the code:
```
class DelayedExtension(Extension, object):
    def __init__(self, *args, **kwargs):
        super(DelayedExtension, self).__init__(*args, **kwargs)
        self._include_hooks = []
        self.include_hook = self._include_hooks.append

    @property
    def include_dirs(self):
            result = self.__dict__['include_dirs'] = list(chain.from_iterable(hook() for hook in self._include_hooks))

            if obj._finalized:
                if self._name in obj._hooks:
                    result = obj._hooks[self._name]() + result

            return result

        def __set__(self, obj, value):
            setattr(obj, '_' + self._name, value)

    include_dirs = DelayedMember('include_dirs')

**Comment by Midnighter** [comment]
Maybe it's such a fringe issue that the readme is the right place for it. I've just recently worked on 2 or 3 projects myself where this would have been useful so I thought, it'd be great if your template provided this.

Have you tried your code above? I'm sure there's a lot more going on with matplotlib, it was simply the only example solution I came across.

**Comment by ionelmc** [comment]
It's not like I'm saying no :-)

I'm only saying "not by default". I'm asking weird questions to understand a bit your usecase.

And yeah, I haven't tested it, did the typos tip you off? :grin: Still, it seems it could work ...

It could even be a "c_extension_numpy", instead of "c_extension_delayed_include" - is that is indeed the sole usecase for this.

**Comment by Midnighter** [comment]
> I'm only saying "not by default".

Absolutely, it should be an opt-in choice.

> It could even be a "c_extension_numpy", instead of "c_extension_delayed_include" - is that is indeed the sole usecase for this.

I like `c_extension_delayed_include` better. Although not very common it might be desirable to include scipy, pandas, bottleneck, numexpr, you name it.

**Comment by ionelmc** [comment]
Do all those libraries have a `.include_dirs()` thing?

**Comment by Midnighter** [comment]
I highly doubt it. Which I suppose defeats the purpose of this to begin with ^^

**Comment by ionelmc** [comment]
Come on, you can't give up this easy :-)

**Comment by Midnighter** [comment]
I'll look into it and get back to you. I'm using your code just for numpy for my current package anyhow. So thank you for that. :)

**Comment by Midnighter** [comment]
With your current code I get the following error right now:

```
Traceback (most recent call last):
  File "setup.py", line 82, in <module>
    for (root, _, _) in os.walk("src")
  File "setup.py", line 83, in <listcomp>
    for path in glob(join(root, "*.pyx" if Cython else "*.c"))
  File "setup.py", line 65, in __init__
    super(DelayedExtension, self).__init__(*args, **kwargs)
  File "/usr/lib/python3.4/distutils/extension.py", line 112, in __init__
    self.include_dirs = include_dirs or []
AttributeError: can't set attribute
```
Not sure why right now.

**Comment by ionelmc** [comment]
Ah, so this is why they used a full descriptor (both `__get__` and `__set__`) ...

This would work:
```python
from setuptools import Extension


class DelayedExtension(Extension, object):
    def __init__(self, *args, **kwargs):
        super(DelayedExtension, self).__init__(*args, **kwargs)
        self._include_dirs_hooks = []
        self._include_dirs = None
        self.include_dirs_hook = self._include_dirs_hooks.append

    @property
    def include_dirs(self):
        if 'include_dirs' not in self.__dict__:
            include_dirs = self.__dict__['include_dirs'] = list(self._include_dirs or [])
            for hook in self._include_dirs_hooks:
                include_dirs.extend(hook())
        return self.__dict__['include_dirs']

    @include_dirs.setter
    def include_dirs(self, value):
        self._include_dirs = value


ext = DelayedExtension('x', ['x.c'])


@ext.include_dirs_hook
def hook():
    import numpy
    print(numpy)
    yield numpy.get_include()


print(ext.include_dirs)
print(ext.include_dirs)
```

Though it's longer.

**Comment by Midnighter** [comment]
This should now be covered by [PEP518 and the `pyproject.toml`](https://www.python.org/dev/peps/pep-0518/).
