### ISSUE TITLE
Blank line at end of cli.py

### ISSUE THREAD

**Issue by dragon788** [ionelmc/cookiecutter-pylibrary#66]
I've been trying to set this up on Windows and making some progress after I actually installed the vcpython27 package to be able to compile extensions. Oddly enough I already had Visual Studio Community 2015 but it was having issues with it not being able to find/use the proper compiler.

After I got all those issues sorted out, I'm getting failures on flake8 about a blank line at the end of cli.py, and some documentation failures with sphinx-build, but those I expect because I'm using it for a non-Github project in a private repo.

**Comment by dragon788** [comment]
Might be related to this question. http://stackoverflow.com/questions/9768139/pep8-conflict-between-w292-and-w391

If you add a - after the final endif to suppress the newline in Jinja2 it fails with the other warning. Dang it all!!!

**Comment by ionelmc** [comment]
I forgot to close :)
