### ISSUE TITLE
keywords in setup.py

### ISSUE THREAD

**Issue by musically-ut** [ionelmc/cookiecutter-pylibrary#68]
I couldn't find relevant documentation on it anywhere, so I am not sure whether `keywords` in `setup.py` can be a list of strings or just a string separated with strings.

In all packages I have seen, it can only be the latter, though the template seems to suggest that it ought to be a list of strings.

Could you please link me to documentation where a list of strings is declared as a valid value for `keywords`?

Thanks!

**Comment by ionelmc** [comment]
See https://docs.python.org/3/distutils/apiref.html?highlight=keywords

**Comment by musically-ut** [comment]
Perfect, thanks!

**Comment by ionelmc** [comment]
The point of the list, and the reason I chose that form, is that it allows you to have spaces in certain keywords and it's subjectively less ambiguous.
