### ISSUE TITLE
Please, add a CHANGELOG.md for the project

### ISSUE THREAD

**Issue by svetlyak40wt** [ionelmc/cookiecutter-pylibrary#7]
Please, add a CHANGELOG.md, so that anybody could track how does `cookiecutter-pylibrary` evolve (or even subscribe to its release notes at <http://allmychanges.com>).

**Comment by ionelmc** [comment]
Is a `CHANGELOG.rst` acceptable (restructured text)?

**Comment by svetlyak40wt** [comment]
Sure.

**Comment by svetlyak40wt** [comment]
I hope, you'll choose a sane datetime format as <http://keepachangelog.com> recommends ;-)

**Comment by ionelmc** [comment]
Unfortunately I don't have releases for this (as cookiecutter just clones the git repo), I can only have "date" releases. What to do here?

**Comment by svetlyak40wt** [comment]
Any software could be sem-versioned regardless of uses it some kind of package manager or not.

**Comment by ionelmc** [comment]
Well I suppose I could at least have some tags around.

**Comment by svetlyak40wt** [comment]
If you'll use tag names which looks like `x.y.z` versions, then allmychanges.com will be able to build release notes from commit messages. This is better than nothing and costs almost nothing.

**Comment by ionelmc** [comment]
I think we can close this, there's a changelog section in the readme.

**Comment by svetlyak40wt** [comment]
Sure, thank you!
