### ISSUE TITLE
travis yml formatting issue

### ISSUE THREAD

**Issue by frostidaho** [ionelmc/cookiecutter-pylibrary#77]
It looks like there is some issue in the travis.yml template

https://gist.github.com/frostidaho/828e018131a6f8e72a24fa2182e99d95

**Comment by ionelmc** [comment]
Oooooops, I had this issue in the past. Hmmmm ... what jinja version do you have?

**Comment by frostidaho** [comment]
2.9.5

**Comment by ionelmc** [comment]
Should be fine now, everything green at https://travis-ci.org/ionelmc/python-nameless/branches

**Comment by frostidaho** [comment]
thanks :)
