### ISSUE TITLE
FR: Allow license selection

### ISSUE THREAD

**Issue by snakescott** [ionelmc/cookiecutter-pylibrary#79]
I'd like to be able to pick e.g. Apache-2 instead of BSD. Would a PR for this be welcome?

**Comment by ionelmc** [comment]
Sure, do it.

**Comment by snakescott** [comment]
I have a PR almost ready and want to validate my fork with Travis before submitting. Unfortunately Travis complains that the build matrix is too big, and so doesn't trigger any builds.

![screen shot 2017-06-03 at 6 53 27 pm](https://cloud.githubusercontent.com/assets/1791531/26758261/0a40d232-488e-11e7-8eeb-48a2a0e799b4.png)

**Comment by ionelmc** [comment]
Make the pr and I'll trim the build,

**Comment by ionelmc** [comment]
Ah whoops, forgot about this. Merged #83 (sorry) in favor of this as it was simpler.
