### ISSUE TITLE
Windows 10, Anaconda, --> tox doesn't work

### ISSUE THREAD

**Issue by sixpearls** [ionelmc/cookiecutter-pylibrary#88]
I'm on windows 10, 64-bit. I have a somewhat old Anaconda with base python version 3.6.0 installed. I have tried to use this template with my root conda env and with a more recent 3.6.2 python env. Even just running through all the default options, running ``tox`` does not run.  Any suggestion?

    C:\Users\<username>\Projects\TEST\python-nameless> tox
    GLOB sdist-make: C:\Users\<username>\Projects\TEST\python-nameless\setup.py
    clean create: C:\Users\<username>\Projects\TEST\python-nameless\.tox\clean
    ERROR: InterpreterNotFound: python3
    check create: C:\Users\<username>\Projects\TEST\python-nameless\.tox\check
    ERROR: InterpreterNotFound: python3
    py27 create: C:\Users\<username>\Projects\TEST\python-nameless\.tox\py27
    ERROR: InterpreterNotFound: python2.7
    py33 create: C:\Users\<username>\Projects\TEST\python-nameless\.tox\py33
    ERROR: InterpreterNotFound: python3.3
    py34 create: C:\Users\<username>\Projects\TEST\python-nameless\.tox\py34
    ERROR: InterpreterNotFound: python3.4
    py35 create: C:\Users\<username>\Projects\TEST\python-nameless\.tox\py35
    ERROR: InterpreterNotFound: python3.5
    py36 create: C:\Users\<username>\Projects\TEST\python-nameless\.tox\py36
    ERROR: InterpreterNotFound: python3.6
    pypy create: C:\Users\<username>\Projects\TEST\python-nameless\.tox\pypy
    ERROR: InterpreterNotFound: pypy
    report create: C:\Users\<username>\Projects\TEST\python-nameless\.tox\report
    ERROR: InterpreterNotFound: python3
    docs create: C:\Users\<username>\Projects\TEST\python-nameless\.tox\docs
    ERROR: InterpreterNotFound: python2.7
    ___________________________________ summary ___________________________________
    ERROR:   clean: InterpreterNotFound: python3
    ERROR:   check: InterpreterNotFound: python3
    ERROR:   py27: InterpreterNotFound: python2.7
    ERROR:   py33: InterpreterNotFound: python3.3
    ERROR:   py34: InterpreterNotFound: python3.4
    ERROR:   py35: InterpreterNotFound: python3.5
    ERROR:   py36: InterpreterNotFound: python3.6
    ERROR:   pypy: InterpreterNotFound: pypy
    ERROR:   report: InterpreterNotFound: python3
    ERROR:   docs: InterpreterNotFound: python2.7

**Comment by sixpearls** [comment]
After googling all day, I finally found the problem AFTER opening an issue.

Good luck, future googler's trying to figure out tox on windows (win10), with conda getting InterpreterNotFound errors. Try this: https://stackoverflow.com/a/30555944

**Comment by gonzalocasas** [comment]
@sixpearls hi! future google'r here! thank you doing this, you saved me long hours of pain and suffering :)
