### ISSUE TITLE
Support for GitHub enterprise URLs

### ISSUE THREAD

**Issue by SterlingPeet** [ionelmc/cookiecutter-pylibrary#93]
Great project!

I am using this cookiecutter for some projects at Georgia Tech, most of which may eventually migrate to GitHub proper.  In the meantime, I have to go through a laborious process to change all the links to point at the enterprise url.  In this particular case, github.com gets changed to github.gatech.edu to convert over.  Is this something would be easy to change?

I don't have any experience writing cookiecutter templates, but I suppose I could try.

**Comment by ionelmc** [comment]
I suppose we could have a `github_domain` variable in cookiecutter.json. Give it a shot if you want.

**Comment by SterlingPeet** [comment]
Seems like this has been addressed 😄
